### ISSUE TITLE
Zorgen voor beter structuur 

### ISSUE THREAD

**Issue by Davidvboxt** [modous/connect-your-tribe-profile-card#1]
Het komt vaak tegen dat je meerdere of soms geen spaties tussen je code in staat. probeer dit te voorkomen voor een betere structuur.

https://github.com/modous/connect-your-tribe-profile-card/blob/867501b74455434cf41b36d88601906a5b449b8c/public/style.css#L67

**Comment by modous** [comment]
aightt
