### ISSUE TITLE
Nav in de header doen?

### ISSUE THREAD

**Issue by Davidvboxt** [modous/connect-your-tribe-profile-card#2]
Ik zie dat je navigatie in meerdere pagina's voorkomt, misschien is het daarom handig om de navigatie dan in de header te zetten? Hierdoor hoef je je navigatie niet 2x te veranderen als je iets wilt aanpassen.

https://github.com/modous/connect-your-tribe-profile-card/blob/867501b74455434cf41b36d88601906a5b449b8c/views/about.ejs#L6

**Comment by modous** [comment]
thnx
